In [6]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.10.0


In [7]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 [==============================] - 1s 0us/step


In [9]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [10]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.66451883,  0.13486344, -0.41911918, -0.2476811 , -0.13841635,
        -0.3692544 , -0.00279213,  0.42108458,  0.4679401 ,  0.29926258]],
      dtype=float32)

In [11]:
tf.nn.softmax(predictions).numpy()

array([[0.05081432, 0.11301952, 0.06494741, 0.07709327, 0.08599427,
        0.0682681 , 0.09848507, 0.15047269, 0.15769096, 0.13321437]],
      dtype=float32)

In [12]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [13]:
loss_fn(y_train[:1], predictions).numpy()

2.6843126

In [14]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [15]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 25s 8ms/step - loss: 0.2979 - accuracy: 0.9129
Epoch 2/5
1875/1875 [==============================] - 14s 8ms/step - loss: 0.1432 - accuracy: 0.9575
Epoch 3/5
1875/1875 [==============================] - 12s 7ms/step - loss: 0.1074 - accuracy: 0.9671
Epoch 4/5
1875/1875 [==============================] - 11s 6ms/step - loss: 0.0879 - accuracy: 0.9727
Epoch 5/5
1875/1875 [==============================] - 11s 6ms/step - loss: 0.0738 - accuracy: 0.9769


In [16]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.0752 - accuracy: 0.9781 - 1s/epoch - 5ms/step


[0.07520991563796997, 0.9781000018119812]

In [18]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [19]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.1379159e-08, 5.6246456e-08, 3.7431812e-05, 9.3863491e-04,
        4.5130563e-10, 5.3139314e-07, 6.5137479e-12, 9.9896932e-01,
        4.9754017e-06, 4.9099548e-05],
       [3.1821348e-10, 2.0420754e-05, 9.9997604e-01, 3.4496286e-06,
        8.4534789e-14, 7.9595310e-08, 1.9414563e-10, 1.1178821e-11,
        8.6687679e-10, 1.2533182e-15],
       [2.3561510e-07, 9.9923372e-01, 5.1792511e-05, 3.7632108e-06,
        1.6886497e-05, 8.0855676e-07, 2.0712025e-06, 6.7625428e-04,
        1.3274906e-05, 1.1551023e-06],
       [9.9883276e-01, 1.9057465e-08, 2.6475682e-04, 2.2435412e-07,
        8.8660693e-07, 7.1577256e-06, 8.6382881e-04, 7.6232336e-06,
        1.0323016e-08, 2.2889546e-05],
       [3.4147354e-06, 4.2213399e-11, 2.0485199e-06, 1.7951111e-08,
        9.9583864e-01, 9.5281285e-09, 5.1606054e-07, 1.8011482e-05,
        1.6791381e-07, 4.1371454e-03]], dtype=float32)>